### ISSUE TITLE
Uninstall Function

### ISSUE THREAD

**Issue by ray-moncada** [bitpay/opencart3-plugin#2]
Hi, I am new to OpenCart but I think the uninstall function needs a change.

In the uninstall function is  

> $this->model_setting_setting->deleteSetting('bitpay');

Should it be

> $this->model_setting_setting->deleteSetting('payment_bitpay');

Thank you,
-Ray

**Comment by pieterpoorthuis** [comment]
Yes, tnx. Fixed in the source code. Release will follow.
