### ISSUE TITLE
Display warning when required PHP plugin is not available

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/opencart3-plugin#3]
This plugin requires the following PHP plugins:
* GMP or BCMATH
* OpenSSL
* JSON
* CURL

The plugin should give the user a warning when a required plugin is not available

**Comment by pieterpoorthuis** [comment]
Currently, when e.g. GMP/BCMATH is not available the plugin crashes when clicking 'install'. A dialog window pops up that says "Error". The ajax call error is GET 505 error on the following URL /admin/index.php?route=extension/extension/payment/install&user_token=9Z9ynDbwRddiUlXNDS3wGMeKYG2mbEEX&extension=bitpay

**Comment by ray-moncada** [comment]
Can you add a list of required php-plugin in the readme and in the Admin dashboard? This will help alot.
