### ISSUE TITLE
Payment page not found

### ISSUE THREAD

**Issue by Fle-zz-xa** [bitpay/opencart3-plugin#7]
After installing the extension via the module the page for payment options cannot be found.
i also uploaded the file with filezilla and still the same issue.

Anyone have a solution ?

**Comment by pieterpoorthuis** [comment]
Which version of OpenCart are you running?
If it's 2.x, you can download the latest release from https://github.com/bitpay/opencart-plugin/releases

**Comment by Fle-zz-xa** [comment]
Versie 2.0.3.1
I used the latest version

**Comment by pieterpoorthuis** [comment]
OpenCart v2.0.x is not supported.
OpenCart v2.1 / v2.2 / v2.3 is supported in https://github.com/bitpay/opencart-plugin/releases
OpenCart v3 is supported in https://github.com/bitpay/opencart3-plugin/releases
