### ISSUE TITLE
Table prefix

### ISSUE THREAD

**Issue by faca5** [bitpay/opencart3-plugin#8]
Error:
Fatal error: Uncaught exception 'Exception' with message 'Error: Table 'oc_setting' doesn't exist<br />Error No: 1146

Line to fix:
                $this->db->query("delete from oc_setting where code='bitpay'");

Solution:
                $this->db->query("delete from ".DB_PREFIX."setting where code='bitpay'");

**Comment by pieterpoorthuis** [comment]
thanks for the report, fixed
